---
- hosts: "{{ openshift_node }}"
  gather_facts: False

  roles:
    # - { role: 'post_install', tags: 'post_install'}
    # - { role: 'persistence', tags: 'persistence'}
    # - { role: 'install_nexus', tags: 'install_nexus'}
    # - { role: 'install_jenkins', tags: 'install_jenkins'}
    - { role: 'install_jaeger', tags: 'install_jaeger'}