sshpw --username=root --plaintext centos
# Firewall configuration
firewall --disabled
selinux --enforcing

# Use network installation
url --url="http://mirror.centos.org/centos/7/os/x86_64/"
network --bootproto=dhcp --device=eth0 --activate --onboot=on
network --bootproto=dhcp --device=eth1 --activate --onboot=on
skipx
rootpw --plaintext centos
auth --useshadow --passalgo=sha512

timezone --utc Europe/Brussels
bootloader --timeout=1 --location=mbr --append="no_timer_check console=ttyS0 console=tty0 net.ifnames=0 biosdevname=0"
clearpart --all
part / --fstype="ext4" --size=10240

#Repos
repo --name=base --baseurl=http://mirror.centos.org/centos/7/os/x86_64/
repo --name=updates --baseurl=http://mirror.centos.org/centos/7/updates/x86_64/
repo --name=extras --baseurl=http://mirror.centos.org/centos/7/extras/x86_64/
repo --name=atomic --baseurl=http://mirror.centos.org/centos/7/atomic/x86_64/adb/
repo --name=hvkvp --baseurl=https://copr-be.cloud.fedoraproject.org/results/gbraad/go-hvkvp/epel-7-x86_64/

shutdown

%packages  --excludedocs --instLangs=en
@core
openssl
bash
centos-logos
docker
dracut
e4fsprogs
efibootmgr
grub2
grub2-efi
kernel
net-tools
parted
shadow-utils
shim
syslinux
hyperv-daemons
cifs-utils
fuse-sshfs
nfs-utils
go-hvkvp
python-setuptools

#Packages to be removed
-aic94xx-firmware
-alsa-firmware
-iprutils
-ivtv-firmware
-iwl100-firmware
-iwl1000-firmware
-iwl105-firmware
-iwl135-firmware
-iwl2000-firmware
-iwl2030-firmware
-iwl3160-firmware
-iwl3945-firmware
-iwl4965-firmware
-iwl5000-firmware
-iwl5150-firmware
-iwl6000-firmware
-iwl6000g2a-firmware
-iwl6000g2b-firmware
-iwl6050-firmware
-iwl7260-firmware
-iwl7265-firmware
-postfix
-rsyslog
%end

%post

# Setting a global Locale for the server
echo "LANG=\"C\"" > /etc/locale.conf

yum remove -y redhat-logos linux-firmware

# Clear yum package and metadata cache
yum clean all


# Show a warning banner when using yum to install software
mv /usr/bin/yum /usr/bin/yum-unsupported
# Place holder for base64 encode yum-wrapper script
cat > yum-wrapper.base64 << EOF
IyEvYmluL3NoCmZ1bmN0aW9uIGhyKCkgewogIHByaW50ZiAnJSpzXG4nICIke0NPTFVNTlM6LSQodHB1dCBjb2xzKX0iICcnIHwgdHIgJyAnIC0KfQoKZnVuY3Rpb24gYmFubmVyKCkgewogIGhyCiAgZWNobyAtZSAiSW5zdGFsbGluZyBhZGRpdGlvbmFsIHBhY2thZ2VzIG9uIHRoZSByb290IGZpbGVzeXN0ZW0gbWlnaHQgZXhjZWVkIHRoZSBhbGxvY2F0ZWQgb3ZlcmxheSBzaXplIGFuZCBsb2NrIHRoZSBNaW5pc2hpZnQgVk0uIFByb2NlZWQgd2l0aCB0aGUgaW5zdGFsbGF0aW9uIGF0IHlvdXIgb3duIHJpc2suIgogIGVjaG8gLWUgIkZvciBtb3JlIGluZm9ybWF0aW9uLCBzZWUgaHR0cHM6Ly9kb2NzLm9wZW5zaGlmdC5vcmcvbGF0ZXN0L21pbmlzaGlmdC90cm91Ymxlc2hvb3RpbmcvdHJvdWJsZXNob290aW5nLW1pc2MuaHRtbCNyb290LWZpbGVzeXN0ZW0tZXhjZWVkcy1vdmVybGF5LXNpemUiCiAgaHIKfQoKYmFubmVyCmlmIGVjaG8gIiRAIiB8IGdyZXAgLWlxICIgLXkiIDsgdGhlbgogIGFuc3dlcj0ieSIKZWxzZQogIGVjaG8gIkFyZSB5b3Ugc3VyZSB5b3Ugd2FudCB0byBjb250aW51ZT8gW3kvTl0iCiAgcmVhZCBhbnN3ZXIKZmkKaWYgZWNobyAiJGFuc3dlciIgfCBncmVwIC1pcSAiXnkiIDsgdGhlbgogICAgeXVtLXVuc3VwcG9ydGVkICRACmZpCg==
EOF
base64 -d < yum-wrapper.base64 > yum-wrapper
rm -f yum-wrapper.base64
chmod +x yum-wrapper
mv yum-wrapper /usr/bin/yum


# Place holder for base64 encode handle-user-data script
cat > handle-user-data.base64 << EOF
IyEvYmluL3NoCgpMQUJFTD1iMmQtZGF0YQpNQUdJQz0iYm9vdDJkb2NrZXIsIHBsZWFzZSBmb3JtYXQtbWUiClVOUEFSVElUSU9ORURfSEQ9Ii9kZXYvJChsc2JsayB8IGdyZXAgZGlzayB8IGN1dCAtZjEgLWQnICcpIgoKIyBGdW5jdGlvbiB0byBtb3VudCBwYXJ0aXRpb25zCm1vdW50X3BhcnRpdGlvbnMoKSB7CiAgICBQQVJUTkFNRT1gZWNobyAiJEJPT1QyRE9DS0VSX0RBVEEiIHwgc2VkICdzLy4qXC8vLydgCiAgICBlY2hvICJtb3VudCBwOiRQQVJUTkFNRSAuLi4iCiAgICBta2RpciAtcCAvbW50LyRQQVJUTkFNRQogICAgaWYgISBtb3VudCAkQk9PVDJET0NLRVJfREFUQSAvbW50LyRQQVJUTkFNRSAyPi9kZXYvbnVsbDsgdGhlbgogICAgICAgICMgZm9yIHNvbWUgcmVhc29uLCBtb3VudCBkb2Vzbid0IGxpa2UgdG8gbW9kcHJvYmUgYnRyZnMKICAgICAgICBCT09UMkRPQ0tFUl9GU1RZUEU9YGJsa2lkIC1vIGV4cG9ydCAkQk9PVDJET0NLRVJfREFUQSB8IGdyZXAgVFlQRT0gfCBjdXQgLWQ9IC1mMmAKICAgICAgICBtb2Rwcm9iZSAkQk9PVDJET0NLRVJfRlNUWVBFIHx8IHRydWUKICAgICAgICB1bW91bnQgLWYgL21udC8kUEFSVE5BTUUgfHwgdHJ1ZQogICAgICAgIG1vdW50ICRCT09UMkRPQ0tFUl9EQVRBIC9tbnQvJFBBUlROQU1FCiAgICBmaQoKICAgICMgQWN0aXZhdGUgc3dhcCBwYXJ0aXRpb24KICAgIGVjaG8gImFjdGl2YXRlIHN3YXAgLi4uIgogICAgc3dhcG9uICIke1VOUEFSVElUSU9ORURfSER9MiIKCiAgICAjIEp1c3QgaW4gY2FzZSwgdGhlIGxpbmtzIHdpbGwgZmFpbCBpZiBub3QKICAgIHVtb3VudCAtZiAvdmFyL2xpYi9kb2NrZXIgfHwgdHJ1ZQogICAgcm0gLXJmIC92YXIvbGliL2RvY2tlciAvdmFyL2xpYi9ib290MmRvY2tlciAvZXRjL2RvY2tlciAvdmFyL2xpYi9taW5pc2hpZnQgL29wdAoKICAgICMgRGV0ZWN0ZWQgYSBkaXNrIHdpdGggYSBub3JtYWwgbGludXggaW5zdGFsbCAoL3Zhci9saWIvZG9ja2VyICsgbW9yZSkpCiAgICBpZiBbICEgLWQgIi92YXIvbGliIiBdOyB0aGVuCiAgICAgICAgbWtkaXIgLXAgL3Zhci9saWIKICAgIGZpCgogICAgaWYgWyAtZCAiL2V0Yy9wa2kvY29uc3VtZXIiIF07IHRoZW4KICAgICAgICBybSAtZnIgL2V0Yy9wa2kvY29uc3VtZXIgL2V0Yy9wa2kvZW50aXRsZW1lbnQgL2V0Yy9wa2kvcHJvZHVjdAogICAgICAgIG1rZGlyIC1wIC9tbnQvJFBBUlROQU1FL2V0Yy9wa2kve2NvbnN1bWVyLGVudGl0bGVtZW50LHByb2R1Y3R9CiAgICAgICAgbG4gLXMgL21udC8kUEFSVE5BTUUvZXRjL3BraS9jb25zdW1lciAvZXRjL3BraS9jb25zdW1lcgogICAgICAgIGxuIC1zIC9tbnQvJFBBUlROQU1FL2V0Yy9wa2kvZW50aXRsZW1lbnQgL2V0Yy9wa2kvZW50aXRsZW1lbnQKICAgICAgICBsbiAtcyAvbW50LyRQQVJUTkFNRS9ldGMvcGtpL3Byb2R1Y3QgL2V0Yy9wa2kvcHJvZHVjdAogICAgZmkKCiAgICBta2RpciAtcCAvbW50LyRQQVJUTkFNRS92YXIvbGliL2RvY2tlcgogICAgbWtkaXIgLXAgL3Zhci9saWIvZG9ja2VyCiAgICBtb3VudCAtLWJpbmQgL21udC8kUEFSVE5BTUUvdmFyL2xpYi9kb2NrZXIgL3Zhci9saWIvZG9ja2VyCiAgICByZXN0b3JlY29uIC1SIC92YXIvbGliL2RvY2tlcgoKICAgIG1rZGlyIC1wIC9tbnQvJFBBUlROQU1FL3Zhci9saWIvYm9vdDJkb2NrZXIKICAgIG1rZGlyIC1wIC92YXIvbGliL2Jvb3QyZG9ja2VyCiAgICBtb3VudCAtLWJpbmQgL21udC8kUEFSVE5BTUUvdmFyL2xpYi9ib290MmRvY2tlciAvdmFyL2xpYi9ib290MmRvY2tlcgoKICAgIG1rZGlyIC1wIC9tbnQvJFBBUlROQU1FL3Zhci9saWIvYm9vdDJkb2NrZXIvZXRjL2RvY2tlcgogICAgbWtkaXIgLXAgL2V0Yy9kb2NrZXIKICAgIG1vdW50IC0tYmluZCAvbW50LyRQQVJUTkFNRS92YXIvbGliL2Jvb3QyZG9ja2VyL2V0Yy9kb2NrZXIgL2V0Yy9kb2NrZXIKCiAgICBta2RpciAtcCAvbW50LyRQQVJUTkFNRS92YXIvbGliL21pbmlzaGlmdAogICAgbWtkaXIgLXAgL3Zhci9saWIvbWluaXNoaWZ0CiAgICBtb3VudCAtLWJpbmQgL21udC8kUEFSVE5BTUUvdmFyL2xpYi9taW5pc2hpZnQgL3Zhci9saWIvbWluaXNoaWZ0CgogICAgbWtkaXIgLXAgL21udC8kUEFSVE5BTUUvb3B0CiAgICBsbiAtcyAvbW50LyRQQVJUTkFNRS9vcHQgL29wdAoKICAgICMgTW92ZSB1c2VyZGF0YSB0byBwZXJzaXN0ZW50IHN0b3JhZ2UKICAgIGlmIFsgLWUgIi91c2VyZGF0YS50YXIiIF07IHRoZW4KICAgICAgICBtdiAvdXNlcmRhdGEudGFyIC92YXIvbGliL2Jvb3QyZG9ja2VyLwogICAgZmkKCiAgICBscyAtbCAvbW50LyRQQVJUTkFNRQp9CgojIEZ1bmN0aW9uIHRvIHBhcnRpb24gYW5kIGZvcm1hdCB0aGUgZGF0YSBkaXNrCnByZXBhcmVfcGFydGlvbnMoKSB7CiAgICAjIENyZWF0ZSB0aGUgcGFydGl0aW9uLCBmb3JtYXQgaXQgYW5kIHRoZW4gbW91bnQgaXQKICAgIGVjaG8gIk5FVyBib290MmRvY2tlciBtYW5hZ2VkIGRpc2sgaW1hZ2UgKCRVTlBBUlRJVElPTkVEX0hEKTogZm9ybWF0dGluZyBpdCBmb3IgdXNlIgoKICAgICMgQWRkIGEgc3dhcCBwYXJ0aXRpb24gKHNvIERvY2tlciBkb2Vzbid0IGNvbXBsYWluIGFib3V0IGl0IG1pc3NpbmcpCiAgICAoZWNobyBuOyBlY2hvIHA7IGVjaG8gMjsgZWNobyA7IGVjaG8gKzEwMDBNIDsgZWNobyB3KSB8IGZkaXNrICRVTlBBUlRJVElPTkVEX0hECiAgICAjIExldCBrZXJuZWwgcmUtcmVhZCBwYXJ0aXRpb24gdGFibGUKICAgIHBhcnRwcm9iZQoKICAgIChlY2hvIHQ7IGVjaG8gODI7IGVjaG8gdykgfCBmZGlzayAkVU5QQVJUSVRJT05FRF9IRAogICAgIyBMZXQga2VybmVsIHJlLXJlYWQgcGFydGl0aW9uIHRhYmxlCiAgICBwYXJ0cHJvYmUKICAgICMgd2FpdCBmb3IgdGhlIHBhcnRpdGlvbiB0byBhY3R1YWxseSBleGlzdCwgdGltZW91dCBhZnRlciBhYm91dCA1IHNlY29uZHMKICAgIGxvY2FsIHRpbWVyPTAKICAgIHdoaWxlIFsgIiR0aW1lciIgLWx0IDEwIC1hICEgLWIgIiR7VU5QQVJUSVRJT05FRF9IRH0yIiBdOyBkbwogICAgICAgIHRpbWVyPSQoKHRpbWVyICsgMSkpCiAgICAgICAgc2xlZXAgMC41CiAgICBkb25lCgogICAgIyBQcmVwYXJlIHRoZSBzd2FwIHBhcnRpdGlvbgogICAgbWtzd2FwICIke1VOUEFSVElUSU9ORURfSER9MiIKCiAgICAjIEFkZCB0aGUgZGF0YSBwYXJ0aXRpb24KICAgIChlY2hvIG47IGVjaG8gcDsgZWNobyAxOyBlY2hvIDsgZWNobyA7IGVjaG8gdykgfCBmZGlzayAkVU5QQVJUSVRJT05FRF9IRAogICAgIyBMZXQga2VybmVsIHJlLXJlYWQgcGFydGl0aW9uIHRhYmxlCiAgICBwYXJ0cHJvYmUKICAgICMgd2FpdCBmb3IgdGhlIHBhcnRpdGlvbiB0byBhY3R1YWxseSBleGlzdCwgdGltZW91dCBhZnRlciBhYm91dCA1IHNlY29uZHMKICAgIHRpbWVyPTAKICAgIHdoaWxlIFsgIiR0aW1lciIgLWx0IDEwIC1hICEgLWIgIiR7VU5QQVJUSVRJT05FRF9IRH0xIiBdOyBkbwogICAgICAgIHRpbWVyPSQoKHRpbWVyICsgMSkpCiAgICAgICAgc2xlZXAgMC41CiAgICBkb25lCgogICAgQk9PVDJET0NLRVJfREFUQT1gZWNobyAiJHtVTlBBUlRJVElPTkVEX0hEfTEiYAogICAgbWtmcy54ZnMgLW4gZnR5cGU9MSAtaSBzaXplPTIwNDggLUwgJExBQkVMICRCT09UMkRPQ0tFUl9EQVRBCn0KCiMgRnVuY3Rpb24gdG8gZXh0cmFjdCB1c2VyZGF0YS50YXIgY29udGFpbmluZyB0aGUgc3NoIGtleXMgaW50byB0aGUgaG9tZSBkaXJlY3RvcnkgL2hvbWUvZG9ja2VyCmhhbmRsZV91c2VyX2RhdGEoKSB7CiAgICAjIEV4dHJhY3QgdGhlIHVzZXJkYXRhIGludG8gZG9ja2VyIHVzZXIgaG9tZSBkaXJlY3RvcnkKICAgIGlmIFsgLWUgIi92YXIvbGliL2Jvb3QyZG9ja2VyL3VzZXJkYXRhLnRhciIgXTsgdGhlbgogICAgICAgIHRhciB4ZiAvdmFyL2xpYi9ib290MmRvY2tlci91c2VyZGF0YS50YXIgLUMgL2hvbWUvZG9ja2VyLyA+IC92YXIvbG9nL3VzZXJkYXRhLmxvZyAyPiYxCiAgICAgICAgcm0gLWYgJy9ob21lL2RvY2tlci9ib290MmRvY2tlciwgcGxlYXNlIGZvcm1hdC1tZScKICAgICAgICBjaG93biAtUiBkb2NrZXI6ZG9ja2VyIC9ob21lL2RvY2tlci8uc3NoCiAgICBlbHNlCiAgICAgICAgZWNobyAiVW5hYmxlIHRvIGZpbmQgdXNlcmRhdGEudGFyIgogICAgICAgIGV4aXQgMQogICAgZmkKfQoKIyBUT0RPIE5lZWQgdG8gbWFrZSBzdXJlIHRvIGhhdmUgL3NiaW4gb24gdGhlIFBBVEguIElzIHRoZXJlIGEgYmV0dGVyIHdheT8KIyBodHRwOi8vc3RhY2tvdmVyZmxvdy5jb20vcXVlc3Rpb25zLzE5OTgzNzEwL3NvbWUtY29tbWFuZHMtbm90LXdyb2tpbmctb24tcmVtb3RlLXNlcnZlcnMtdGhyb3VnaC1zc2gtc2hlbGwKIyBodHRwczovL2dpdGh1Yi5jb20vTGFsYXRlbmR1TW9oYW50eS9jZW50b3MtbGl2ZS1pc28vaXNzdWVzLzExCmVjaG8gJ1BBVEg9JFBBVEg6L3NiaW4nID4+IC9ob21lL2RvY2tlci8uYmFzaHJjCgojIElmIHRoZXJlIGlzIGEgcGFydGl0aW9uIHdpdGggYGJvb3QyZG9ja2VyLWRhdGFgIGFzIGl0cyBsYWJlbCB3ZSBhcmUgZGVhbGluZyB3aXRoCiMgYW4gYWxyZWFkeSBib290c3RyYXBwZWQgZG9ja2VyLW1hY2hpbmUuIEp1c3QgbWFrZSBzdXJlIHRvIG1vdW50IGRhdGEgcGFydGl0aW9uIGFuZCB0byB1bnBhY2sKIyB1c2VyZGF0YS50YXIuIFJlbWVtYmVyLCAvaG9tZS9kb2NrZXIgaXMgbm90IHBlcnNpc3RlbnQKQk9PVDJET0NLRVJfREFUQT1gYmxraWQgLW8gZGV2aWNlIC1sIC10IExBQkVMPSRMQUJFTGAKaWYgWyAtbiAiJEJPT1QyRE9DS0VSX0RBVEEiIF07IHRoZW4KICAgIG1vdW50X3BhcnRpdGlvbnMKICAgIGhhbmRsZV91c2VyX2RhdGEKICAgIGV4aXQgMApmaQoKIyBUZXN0IGZvciBvdXIgbWFnaWMgc3RyaW5nIChpdCBtZWFucyB0aGF0IHRoZSBkaXNrIHdhcyBtYWRlIGJ5IC4vYm9vdDJkb2NrZXIgaW5pdCkKSEVBREVSPWBkZCBpZj0kVU5QQVJUSVRJT05FRF9IRCBicz0xIGNvdW50PSR7I01BR0lDfSAyPi9kZXYvbnVsbGAKaWYgWyAiJEhFQURFUiIgPSAiJE1BR0lDIiBdOyB0aGVuCiAgICAjIFJlYWQgL3VzZXJkYXRhLnRhciB3aXRoIHNzaCBrZXlzIGFuZCBwbGFjZSBpdCB0ZW1wb3JhcmlseSB1bmRlciAvCiAgICBkZCBpZj0kVU5QQVJUSVRJT05FRF9IRCBvZj0vdXNlcmRhdGEudGFyIGJzPTEgY291bnQ9NDA5NiAyPi9kZXYvbnVsbAoKICAgIHByZXBhcmVfcGFydGlvbnMKICAgIG1vdW50X3BhcnRpdGlvbnMKICAgIGhhbmRsZV91c2VyX2RhdGEKICAgIGV4aXQgMApmaQo=
EOF
base64 -d < handle-user-data.base64 > handle-user-data
rm -f handle-user-data.base64
chmod +x handle-user-data
mv handle-user-data /usr/local/bin/minishift-handle-user-data

# Handle user data (systemd service)
cat > handle-user-data-service.base64 << EOF
IyAgVGhpcyBmaWxlIGlzIHBhcnQgb2YgTWluaXNoaWZ0CgpbVW5pdF0KRGVzY3JpcHRpb249TWluaXNoaWZ0IGhhbmRsZSB1c2VyIGRhdGEKQ29uZGl0aW9uRmlsZUlzRXhlY3V0YWJsZT0vdXNyL2xvY2FsL2Jpbi9taW5pc2hpZnQtaGFuZGxlLXVzZXItZGF0YQpCZWZvcmU9ZG9ja2VyLnNlcnZpY2UKCltTZXJ2aWNlXQpUeXBlPW9uZXNob3QKRXhlY1N0YXJ0PS91c3IvbG9jYWwvYmluL21pbmlzaGlmdC1oYW5kbGUtdXNlci1kYXRhClRpbWVvdXRTZWM9MApSZW1haW5BZnRlckV4aXQ9eWVzCgpbSW5zdGFsbF0KV2FudGVkQnk9bXVsdGktdXNlci50YXJnZXQK
EOF
base64 -d < handle-user-data-service.base64 > handle-user-data.service
rm handle-user-data-service.base64
mv handle-user-data.service /usr/lib/systemd/system/minishift-handle-user-data.service


# Set IP address based on settings or hvkvp (Hyper-V)
cat > set-ipaddress.base64 << EOF
IyEvYmluL2Jhc2gKc2hvcHQgLXMgbnVsbGdsb2IKCkhWTkVUV09SS0lORz1gaHZrdnAgLWtleSBQUk9WSVNJT05fTkVUV09SS0lOR2AKSFZLVlBfUkVTVUxUPSQ/CgppZiBbICRIVktWUF9SRVNVTFQgLWVxIDAgXSAmJiBbICEgLXogIiRIVk5FVFdPUktJTkciIF07IHRoZW4KICBlY2hvICJIeXBlci1WIG5ldHdvcmsgY29uZmlndXJhdGlvbiBhdmFpbGFibGUgLi4uIgogIGVjaG8gJEhWTkVUV09SS0lORyB8IGJhc2U2NCAtLWRlY29kZSA+IC92YXIvbGliL21pbmlzaGlmdC9uZXR3b3JraW5nCmZpCgpORVRXT1JLX1NDUklQVFM9KC92YXIvbGliL21pbmlzaGlmdC9uZXR3b3JraW5nKikKCmlmIFsgJHsjTkVUV09SS19TQ1JJUFRTW0BdfSAtZ3QgMCBdOyB0aGVuIAoKICBmb3IgRklMRSBpbiAke05FVFdPUktfU0NSSVBUU1tAXX0KICBkbwoKICAgIHVuc2V0IERFVklDRSBJUEFERFIgTkVUTUFTSyBHQVRFV0FZIEROUzEgRE5TMiBVU0VESENQCiAgICBlY2hvICJQcm9jZXNzaW5nIG5ldHdvcmsgY29uZmlndXJhdGlvbiBmaWxlICckRklMRScgLi4uIgoKICAgIC4gIiRGSUxFIgoKICAgIGlmIFsgISAteiAiJERJU0FCTEVEIiBdIHx8IFsgLXogIiRERVZJQ0UiIF07IHRoZW4KCiAgICAgICBlY2hvICJEZXZpY2UgaXMgZGlzYWJsZWQgb3Igbm90IHNldDogJyRERVZJQ0UnIgogICAgICAgY29udGludWUKCiAgICBmaQoKICAgIGVjaG8gIkRldmljZSAnJERFVklDRScgaXMgZW5hYmxlZCIKICAgIGlwIGxpbmsgc2V0IGRldiAkREVWSUNFIHVwCgogICAgaWYgWyAhIC16ICIkVVNFREhDUCIgXTsgdGhlbgoKICAgICAgZWNobyAiVXNlIERIQ1AgZm9yIGRldmljZSAnJERFVklDRSciCiAgICAgIGRoY2xpZW50IFwKICAgICAgICAtcGYgL3Zhci9ydW4vZGhjbGllbnQtJERFVklDRS5waWQgXAogICAgICAgIC1sZiAvdmFyL2xpYi9kaGNsaWVudC9kaGNsaWVudC0kREVWSUNFLWxlYXNlIFwKICAgICAgICAtNCAkREVWSUNFCgogICAgZWxzZQogICAKICAgICAgaWYgWyAhIC16ICIkSVBBRERSIiBdICYmIFsgISAteiAiJE5FVE1BU0siIF07IHRoZW4gCiAgICAgICAgZWNobyAiU2V0IElQIGFkZHJlc3MgJElQQUREUi8kTkVUTUFTSyBvbiBkZXZpY2UgJyRERVZJQ0UnIgogICAgICAgIGlwIGFkZHJlc3MgYWRkICRJUEFERFIvJE5FVE1BU0sgZGV2ICRERVZJQ0UKICAgICAgZmkKCiAgICAgIFsgISAteiAiJEdBVEVXQVkiIF0gJiYgaXAgcm91dGUgYWRkIGRlZmF1bHQgdmlhICRHQVRFV0FZIGRldiAkREVWSUNFCiAgICAgIFsgISAteiAiJEROUzEiIF0gJiYgZWNobyAibmFtZXNlcnZlciAkRE5TMSIgPiAgL2V0Yy9yZXNvbHYuY29uZgogICAgICBbICEgLXogIiRETlMyIiBdICYmIGVjaG8gIm5hbWVzZXJ2ZXIgJEROUzIiID4+IC9ldGMvcmVzb2x2LmNvbmYKCiAgICBmaQoKICBkb25lCgplbHNlCgogIGVjaG8gIk5vIG5ldHdvcmsgY29uZmlndXJhdGlvbiBmaWxlcyBmb3VuZCIKICBzeXN0ZW1jdGwgc3RhcnQgTmV0d29ya01hbmFnZXIKCmZpCgpleGl0IDAKCg==
EOF
base64 -d < set-ipaddress.base64 > set-ipaddress
rm set-ipaddress.base64
chmod +x set-ipaddress
mv set-ipaddress /usr/local/bin/minishift-set-ipaddress

# Set IP address (systemd service)
cat > set-ipaddress-service.base64 << EOF
IyAgVGhpcyBmaWxlIGlzIHBhcnQgb2YgTWluaXNoaWZ0CgpbVW5pdF0KRGVzY3JpcHRpb249TWluaXNoaWZ0IElQIGFzc2lnbm1lbnQKQ29uZGl0aW9uRmlsZUlzRXhlY3V0YWJsZT0vdXNyL2xvY2FsL2Jpbi9taW5pc2hpZnQtc2V0LWlwYWRkcmVzcwpBZnRlcj1taW5pc2hpZnQtaGFuZGxlLXVzZXItZGF0YS5zZXJ2aWNlClJlcXVpcmVzPW5ldHdvcmsudGFyZ2V0CgpbU2VydmljZV0KVHlwZT1vbmVzaG90CkV4ZWNTdGFydD0vdXNyL2xvY2FsL2Jpbi9taW5pc2hpZnQtc2V0LWlwYWRkcmVzcwpUaW1lb3V0U2VjPTAKCltJbnN0YWxsXQpXYW50ZWRCeT1tdWx0aS11c2VyLnRhcmdldAo=
EOF
base64 -d < set-ipaddress-service.base64 > set-ipaddress.service
rm set-ipaddress-service.base64
mv set-ipaddress.service /usr/lib/systemd/system/minishift-set-ipaddress.service


# Systemd configuration
systemctl disable kdump
systemctl disable rc-local
systemctl disable network
systemctl disable NetworkManager
systemctl disable NetworkManager-dispatcher
systemctl disable NetworkManager-wait-online
systemctl enable minishift-handle-user-data
systemctl enable minishift-set-ipaddress
systemctl enable docker


# Clean
rm -rf /usr/lib/locale/locale-archive
rm -rf /var/cache/yum/*

%end

