- name: Delete Project
  shell: oc delete project {{ item }} --ignore-not-found=true --force --now
  with_items:
    - infra

- pause:
    seconds: 20

- name: Create projects
  shell: oc new-project {{ item }}
  with_items:
    - infra