- name: Add cluster-admin privileges to admin user
  shell: oc adm policy add-cluster-role-to-user cluster-admin admin

- name: Delete Project
  shell: oc delete project {{ item }} --ignore-not-found=true --force --now
  with_items:
    - infra

- pause:
    seconds: 20

- name: Create projects
  shell: oc new-project {{ item }}
  with_items:
    - infra